name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Package
        run: mvn package -DskipTests

      - name: List files in target directory (debug)
        run: ls -al target/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Render Deployment via Deploy Hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cs36n2pu0jms7395j8p0?key=Hg6tRtkLWEA"
